"""Initial migration

Revision ID: 6fd8514a2e39
Revises: 
Create Date: 2024-07-09 14:51:57.460734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd8514a2e39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_round_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_representation', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_round_info', schema=None) as batch_op:
        batch_op.drop_column('vector_representation')

    # ### end Alembic commands ###
